services:
  vulkan2blazor:
    image: privatech/vulkan2:latest
    ports:
        - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
#      ASPNETCORE_URLS: "http://localhost:8080"
      ConnectionStrings__Vulkan2Context: 'Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}'
    depends_on:
      postgres:
        condition: service_healthy
#    volumes:
#      - vulkan2:/home/app/.aspnet/DataProtection-Keys
      
  postgres:
    image: postgres
    restart: always
    user: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
        
volumes:
    postgres:
#    vulkan2:

